### ISSUE TITLE
Several Elemental Effects are not killing player

### ISSUE THREAD

**Issue by RocketRaccoon7** [blaxxun-boop/DarwinAwards#2]
Smoke inhalation, drowning, and freezing work, but burning (fire) and poison will not kill the player. Player will hit a health value where health-damage > 0 health remaining and not count the final tick which should kill the player. Instead it will stay at this health no matter how long the poison or fire effect tick off health. 

Really enjoy the fun of this mod even with the current issue, but in certain areas it's very noticeable these effects keep the player alive when they shouldn't and it can be abused.

edit: Recorded a video example of the fire and poison issue to help: https://www.youtube.com/watch?v=1OSE1Q6PkL0

**Comment by blaxxun-boop** [comment]
Hi,

can you please share your log, after this happened?

Cheers.

**Comment by RocketRaccoon7** [comment]
Certainly! There's definitely an error showing up, so hopefully it helps you.

[valheimerror.txt](https://github.com/blaxxun-boop/DarwinAwards/files/9084917/valheimerror.txt)

**Comment by blaxxun-boop** [comment]
Hey,

looks like this happens, if there is an empty string in your AwardCategories.yml.

Cheers.

**Comment by RocketRaccoon7** [comment]
I will test that by using the default one, not the one I added several more to, and see if the problem disappears.

Thanks.

edit: found the empty string. Testing now.

**Comment by RocketRaccoon7** [comment]
Problem is resolved, fixing empty string under Element group resolved the issue. Thank you for the help!
