### ISSUE TITLE
Message on death is "R.I.P. {user}" only

### ISSUE THREAD

**Issue by odd-1** [blaxxun-boop/DarwinAwards#3]
Hi there,

I installed DarwinAwards again, unfortunately this time the only message we get in game and on Discord is "R.I.P. {user}". Is there a setting I'm missing or is this no longer working?

This behaviour is consistant on a local game, a local server game and a dedicated server.

Valheim, v0.211.11
BepInExPack, v5.4.1901
DarwinAwards, v1.0.4

We are running a couple of other mods:
Advize/PlantEverything/
AeehyehssReeper/ChaosArmor/
ASharpPen/Custom_Raids/
ASharpPen/Drop_That/
ASharpPen/Spawn_That/
ASharpPen/This_Goes_Here/
DasSauerkraut/Terraheim/
EmrikNorth_and_Aedenthorn/JotunnBackpacks/
Fantu/PopVillages/
Fantu/Sages_Vault/
GoldenJude/Blacksmiths_tools/
GoldenJude/Judes_Equipment/
HugotheDwarf/Hugos_Armory/
Horem/Minotaurs/
HugotheDwarf/More_and_Modified_Player_Cloth_Colliders/
HugotheDwarf/Shapekeys_and_More/
Huntardys/EpicValheimsAdditions/
JereKuusela/Server_Sync_Fix/
KaceCottam/TripleBronze/
MaxiMods/MultiCraft/
Menthus/Useful_Paths/
mgway/PaddlePower/
MonsterLabZ/MonsterLabZ/
neurodr0me/RRRCore/
neurodr0me/RRRMonsters/
neurodr0me/RRRNpcs/
Nexus/FarmGrid/
OdinPlus/ChickenBoo/
OdinPlus/KnarrTheTrader/
OdinPlus/OrcHorde/
OdinPlus/PotionPlus/
OdinPlus/TripleBronzeJVL/
RandyKnapp/EpicLoot/
RandyKnapp/ExtendedItemDataFramework/
remmiz/SimpleRecycling_Fixed/
Rex_Mods/Trials_of_Odin/
RockerKitten/BoneAppetit/
Smoothbrain/CreatureLevelAndLootControl/
Smoothbrain/DarwinAwards/
Smoothbrain/DualWield/
thedefside/Journey_To_Valhalla/
thedefside/jtv_biomes/
thedefside/RecipeCustomizer/
thedefside/WeaponCustomizer/
UnJohnny/Outsiders/
ValheimModding/Jotunn/

Can you please help me?

**Comment by blaxxun-boop** [comment]
That's the fallback text. Just means that the YAML file wasn't loaded properly. You can check the logs to see why.

**Comment by odd-1** [comment]
I had to search a little deeper for the logs, but I found it. The yaml file is in 'plugin' and not 'config'. When I moved it, it worked. I installed this mod through Thunderstore Mod Manager, might have been something with installation...

Thank you very much!
